#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.2~bpo10+1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'omxplayer0.service' 'omxplayer1.service' 'omxplayer2.service' >/dev/null || true
fi
# End automatically added section
