Document: vplayer
Title: Debian vplayer Manual
Author: <insert document author here>
Abstract: This manual describes what vplayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vplayer/vplayer.sgml.gz

Format: postscript
Files: /usr/share/doc/vplayer/vplayer.ps.gz

Format: text
Files: /usr/share/doc/vplayer/vplayer.text.gz

Format: HTML
Index: /usr/share/doc/vplayer/html/index.html
Files: /usr/share/doc/vplayer/html/*.html
